formatter: markdown table

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sections:
  show:
    - requirements
    - inputs
    - outputs

settings:
  anchor: true
  default: true
  escape: false
  hide-empty: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
